version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=auth_db
    ports:
      - "3310:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - microservices-network
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  eureka-server:
    build: ./eureka-server
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - microservices-network
    depends_on:
      mysql-db:
        condition: service_healthy
    restart: unless-stopped

  ms-auth-service:
    build: ./ms-auth-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - DB_URL=jdbc:mysql://mysql-db:3306/auth_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
      - DB_USERNAME=root
      - DB_PASSWORD=1234
      - DB_DRIVER_CLASS=com.mysql.cj.jdbc.Driver
      - SERVER_PORT=8080
      - JWT_SECRET=a1b2c3d4e5f6g7h8i9j0k1l2m3n4o5p6q7r8s9t0u1v2w3x4y5z6a7b8c9d0e1f2
      - JWT_EXPIRATION=86400000
      - ADMIN_API_KEY=admin123
      - LOG_LEVEL=INFO
      - APP_LOG_LEVEL=DEBUG
    depends_on:
      mysql-db:
        condition: service_healthy
      eureka-server:
        condition: service_started
    networks:
      - microservices-network
    restart: unless-stopped

  ms-patient-service:
    build: ./ms-patient-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - DB_URL=jdbc:mysql://mysql-db:3306/patient_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
      - DB_USERNAME=root
      - DB_PASSWORD=1234
      - DB_DRIVER_CLASS=com.mysql.cj.jdbc.Driver
      - SERVER_PORT=8081
      - JWT_SECRET=a1b2c3d4e5f6g7h8i9j0k1l2m3n4o5p6q7r8s9t0u1v2w3x4y5z6a7b8c9d0e1f2
      - JWT_EXPIRATION=86400000
      - ADMIN_API_KEY=admin123
      - LOG_LEVEL=INFO
      - APP_LOG_LEVEL=DEBUG
    depends_on:
      mysql-db:
        condition: service_healthy
      eureka-server:
        condition: service_started
    networks:
      - microservices-network
    restart: unless-stopped

  ms-medico-service:
    build: ./ms-medico-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - DB_URL=jdbc:mysql://mysql-db:3306/medico_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
      - DB_USERNAME=root
      - DB_PASSWORD=1234
      - DB_DRIVER_CLASS=com.mysql.cj.jdbc.Driver
      - SERVER_PORT=8083
      - JWT_SECRET=a1b2c3d4e5f6g7h8i9j0k1l2m3n4o5p6q7r8s9t0u1v2w3x4y5z6a7b8c9d0e1f2
      - JWT_EXPIRATION=86400000
      - ADMIN_API_KEY=admin123
      - LOG_LEVEL=INFO
      - APP_LOG_LEVEL=DEBUG
    depends_on:
      mysql-db:
        condition: service_healthy
      eureka-server:
        condition: service_started
    networks:
      - microservices-network
    restart: unless-stopped

  ms-citas-service:
    build: ./ms-citas-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - DB_URL=jdbc:mysql://mysql-db:3306/citas_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
      - DB_USERNAME=root
      - DB_PASSWORD=1234
      - DB_DRIVER_CLASS=com.mysql.cj.jdbc.Driver
      - SERVER_PORT=8082
      - JWT_SECRET=a1b2c3d4e5f6g7h8i9j0k1l2m3n4o5p6q7r8s9t0u1v2w3x4y5z6a7b8c9d0e1f2
      - JWT_EXPIRATION=86400000
      - ADMIN_API_KEY=admin123
      - LOG_LEVEL=INFO
      - APP_LOG_LEVEL=DEBUG
    depends_on:
      mysql-db:
        condition: service_healthy
      eureka-server:
        condition: service_started
    networks:
      - microservices-network
    restart: unless-stopped

  gateway:
    build: ./gateway
    ports:
      - "8900:8900"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-server:8761/eureka/
    depends_on:
      eureka-server:
        condition: service_started
      ms-auth-service:
        condition: service_started
      ms-patient-service:
        condition: service_started
      ms-medico-service:
        condition: service_started
      ms-citas-service:
        condition: service_started
    networks:
      - microservices-network
    restart: unless-stopped

volumes:
  mysql_data:

networks:
  microservices-network:
    driver: bridge
