version: '3.8'

services:
  eureka-server:
    build: ./eureka-server
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - microservices-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  ms-auth-service:
    build: ./ms-auth-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - DB_URL=jdbc:mysql://mysql-db:3306/auth_db
      - DB_USERNAME=root
      - DB_PASSWORD=password
      - DB_DRIVER_CLASS=com.mysql.cj.jdbc.Driver
      - SERVER_PORT=8080
      - JWT_SECRET=mySecretKey
      - JWT_EXPIRATION=86400000
      - ADMIN_API_KEY=admin123
      - LOG_LEVEL=INFO
      - APP_LOG_LEVEL=DEBUG
    depends_on:
      - eureka-server
      - mysql-db
    networks:
      - microservices-network

  ms-patient-service:
    build: ./ms-patient-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - DB_URL=jdbc:mysql://mysql-db:3306/patient_db
      - DB_USERNAME=root
      - DB_PASSWORD=password
      - DB_DRIVER_CLASS=com.mysql.cj.jdbc.Driver
      - SERVER_PORT=8081
      - JWT_SECRET=mySecretKey
      - JWT_EXPIRATION=86400000
      - ADMIN_API_KEY=admin123
      - LOG_LEVEL=INFO
      - APP_LOG_LEVEL=DEBUG
    depends_on:
      - eureka-server
      - mysql-db
    networks:
      - microservices-network

  ms-medico-service:
    build: ./ms-medico-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - DB_URL=jdbc:mysql://mysql-db:3306/medico_db
      - DB_USERNAME=root
      - DB_PASSWORD=password
      - DB_DRIVER_CLASS=com.mysql.cj.jdbc.Driver
      - SERVER_PORT=8083
      - JWT_ISSUER_URI=http://ms-auth-service:8080
      - LOG_LEVEL=INFO
      - APP_LOG_LEVEL=DEBUG
    depends_on:
      - eureka-server
      - mysql-db
    networks:
      - microservices-network

  ms-citas-service:
    build: ./ms-citas-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - DB_URL=jdbc:mysql://mysql-db:3306/citas_db
      - DB_USERNAME=root
      - DB_PASSWORD=password
      - DB_DRIVER_CLASS=com.mysql.cj.jdbc.Driver
      - SERVER_PORT=8082
      - JWT_ISSUER_URI=http://ms-auth-service:8080
      - LOG_LEVEL=INFO
      - APP_LOG_LEVEL=DEBUG
    depends_on:
      - eureka-server
      - mysql-db
    networks:
      - microservices-network

  gateway:
    build: ./gateway
    ports:
      - "8900:8900"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-server:8761/eureka/
    depends_on:
      - eureka-server
      - ms-auth-service
      - ms-patient-service
      - ms-medico-service
      - ms-citas-service
    networks:
      - microservices-network

  mysql-db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=auth_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - microservices-network

volumes:
  mysql_data:

networks:
  microservices-network:
    driver: bridge